In [1]:
import os
import yaml
import pandas as pd
from IPython.display import display
import util as ut
import matplotlib.pyplot as plt
import shutil
import numpy as np
res_dir = 'res/'

In [3]:
data_names = ['movie_companies.note', 'name.name', 'title.title']
models = ['CLIQUE', 'CLIQUE-PACK', 'CLIQUE-PACK-ALL', 'LPLM']
workloads = ['CEB']
measures = ['avg', 'q050', 'q090', 'q099', 'q100']

for workload in workloads:
    res_dict = {}
    for data_name in data_names:
        for model in models:
            #### Get only one stat ####
            # stat_path = os.path.join(res_dir, data_name, workload, 'stat', model, '0', 'stat.yml')
            # # print(stat_path)
            # if os.path.exists(stat_path):
            #     stat_dict = yaml.load(open(stat_path), Loader=yaml.FullLoader)
            #     stat_func = lambda x: stat_dict[x]
            # else:
            #     stat_func = lambda x: None

            #### Get average stat ####
            stat_dicts = []
            for trial in [0, 1, 2]:
                stat_path = os.path.join(res_dir, data_name, workload, 'stat', model, '0', 'stat.yml')
                # print(stat_path)
                if os.path.exists(stat_path):
                    stat_dict = yaml.load(open(stat_path), Loader=yaml.FullLoader)
                    stat_dicts.append(stat_dict)
            if len(stat_dicts) > 0:
                stat_func = lambda x: np.average([stat_dict[x] for stat_dict in stat_dicts])
            else:
                stat_func = lambda x: None
            
            #### make res_dict
            for measure in measures:
                if (data_name, measure) not in res_dict:
                    res_dict[(data_name, measure)] = []
                res_dict[(data_name, measure)].append(stat_func(measure))
    df = pd.DataFrame(res_dict, index=models)
    df = df.style.format(na_rep='', precision=2)
    # print(f"{workload =}")
    display(df)